### ISSUE TITLE
GUI - form input padding

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1184]
Hi,

The parent div of input in TestCaseScript.jsp  have .has-feedback class 

```css
.has-feedback .form-control {
    padding-right: 42.5px;
}
```
It's useful if we have icon like 

![image](https://cloud.githubusercontent.com/assets/995694/22585531/90682184-e9f8-11e6-92e9-1a0cf81c1746.png)

here we lose space : 
 
![image](https://cloud.githubusercontent.com/assets/995694/22585512/72e5dfd4-e9f8-11e6-88b5-04cb1ae56b30.png) << here

without has-feedback

![image](https://cloud.githubusercontent.com/assets/995694/22585552/ab3b8ff0-e9f8-11e6-8521-7b2827803098.png) << here
