### ISSUE TITLE
Port 4848 already in use

### ISSUE THREAD

**Issue by kileek** [cerberustesting/cerberus-source#1924]
Hello,

I have an issue with the installation of the last version Cerberus on a windows 10 pro
When i launch my cmd : docker -compose -f default-with-selenium up
i got the error message of the fact that the port 4848 is already so glassfish can't start .
i try to modify the binding port in .yml but nothing change :/

Do you have any idea plz ?

Ps: here's my .yml ( where is no change because the previous didn't worked ^^' )
```
version: '2'
services:
  cerberus-db-mysql:
    image: cerberustesting/cerberus-db-mysql:latest
    expose:
      - "3306"
    ports:
      - "13306:3306"
    volumes:
      - ./localdata/mysql-db:/var/lib/mysql
 #      - /etc/localtime:/etc/localtime:ro
    restart: always
  cerberus-as-glassfish:
    image: cerberustesting/cerberus-as-glassfish:latest
    environment:
      - DATABASE_HOST=cerberus-db-mysql
      - DATABASE_PORT=13306
      - GLASSFISH_DOMAIN=cerberus
# If you want custom glasfish admin password. It's recommanded for a production instance
#      - GLASSFISH_ADMIN_PASSWORD=custompassword
    ports:
      - "18080:8080"
      - "14848:4848"
    volumes:
      - ./localdata/server:/glassfish5/glassfish/domains/cerberus  # allow to persist database pool connection / custom glassfish settings
#      - ./localdata/lib:/tmp/lib/ # allow to add jdbc library to connect database to cerberus. Uncomment only if folder not empty.
      - ./localdata/cerberusmedia:/opt/CerberusMedias/
 #      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - cerberus-db-mysql
    links:
      - cerberus-db-mysql
  # Selenium-related services
  selenium-hub:
    image: selenium/hub:latest
    expose:
      - "4444"
    ports:
      - "14444:4444"
 #    volumes:
 #      - /etc/localtime:/etc/localtime:ro
    restart: always
  selenium-node-firefox:
    image: selenium/node-firefox-debug:latest
    environment:
      HUB_HOST: selenium-hub
    expose:
      - "5900"
    ports:
      - "15900:5900"
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
    restart: always
  selenium-node-chrome:
    image: selenium/node-chrome-debug:latest
    environment:
      HUB_HOST: selenium-hub
    expose:
      - "5900"
    ports:
      - "15901:5900"
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
    restart: always
```

**Comment by vertigo17** [comment]
I already got that issue.
On glassfish image, try to remove the volume
./localdata/server:/glassfish5/glassfish/domains/cerberus

**Comment by MToussaint61** [comment]
Ok so u just remove this line from the file and relaunch the docker compose ?
I mean there is no need to change the admin's port of glassfish right ?

Thank you for your quick response

**Comment by kileek** [comment]
Ok so u just remove this line from the file and relaunch the docker compose ?
I mean there is no need to change the admin's port of glassfish right ?

Thank you for your quick response

**Comment by kileek** [comment]
I tried to comment or remove the line but i've got this error this time.
![capture2](https://user-images.githubusercontent.com/14565233/50956382-d070bd00-14bb-11e9-98a6-2b5786b07afa.JPG)

Do i have to download any other web server ?

**Comment by vertigo17** [comment]
Looks like the database is not started. Can you check that ?

**Comment by kileek** [comment]
I am pretty new in the use of docker and his features so i don't how can i check that ?
Realy sorry

**Comment by nicodeur** [comment]
Hello,

can you send us the result of : `docker-compose ps` on folder you run cerberus please ?

**Comment by kileek** [comment]
In the folder where i laucn the docker-compose [...] up cmd when i launch the docker-compose ps i got this result.
![capture3](https://user-images.githubusercontent.com/14565233/50973549-725ace80-14e9-11e9-8c95-eea6df91b74e.JPG)

**Comment by nicodeur** [comment]
sorry, this cmd please : `docker -compose -f default-with-selenium ps`

**Comment by nicodeur** [comment]
All your containers has closed : 

type first  : `docker-compose -f default-with-selenium up -d`
wait the error with  : `docker-compose -f default-with-selenium logs -f`

test url : http://localhost:18080/Cerberus

if it doesn't work, type : `docker-compose -f default-with-selenium ps` and send us the result.

**Comment by kileek** [comment]
Ok i can't access to the cerberus site with localhost but i got a database error .
![capture6](https://user-images.githubusercontent.com/14565233/50977297-4abc3400-14f2-11e9-992f-e547c579dc16.JPG)


![capture7](https://user-images.githubusercontent.com/14565233/50977336-5c054080-14f2-11e9-8009-aa57a35de9b2.JPG)


![capture8](https://user-images.githubusercontent.com/14565233/50977407-81924a00-14f2-11e9-878d-167213af19d0.JPG)

**Comment by nicodeur** [comment]
Ok, can you just send us database log with this cmd : 

`docker-compose -f default-with-selenium logs -f cerberus-db-mysql` ??

**Comment by kileek** [comment]
This is the last message i got in the logs, tell me if you need more.
![mysql6](https://user-images.githubusercontent.com/14565233/50980451-008a8100-14f9-11e9-970e-3181d945defe.JPG)

**Comment by nicodeur** [comment]
I just find you problem :  

into this section , replace `DATABASE_PORT=13306` by `DATABASE_PORT=3306` 
```
  cerberus-as-glassfish:
    image: cerberustesting/cerberus-as-glassfish:latest
    environment:
      - DATABASE_HOST=cerberus-db-mysql
      - DATABASE_PORT=13306
      - GLASSFISH_DOMAIN=cerberus
# If you want custom glasfish admin password. It's recommanded for a production instance
#      - GLASSFISH_ADMIN_PASSWORD=custompassword
    ports:
      - "18080:8080"
      - "14848:4848"
    volumes:
      - ./localdata/server:/glassfish5/glassfish/domains/cerberus  # allow to persist database pool connection / custom glassfish settings
#      - ./localdata/lib:/tmp/lib/ # allow to add jdbc library to connect database to cerberus. Uncomment only if folder not empty.
      - ./localdata/cerberusmedia:/opt/CerberusMedias/
 #      - /etc/localtime:/etc/localtime:ro
```
