### ISSUE TITLE
Error running test case on fresh install

### ISSUE THREAD

**Issue by futuo** [cerberustesting/cerberus-source#1990]
Hi! Just installed Cerberus 4.0 and I'm having problems running a test case.

The steps I took were as follows:
- Installed Cerberus 4.0 running on MariaDB and Glassfish4
- Followed the interactive tutorials to create a system, environment, application, robot and test case
- Ran the selenium docker image selenium/standalone-chrome with the flag -p 4444:4444 on the same machine Cerberus is running

Some info about the system:
distro: CentOS Linux release 7.6.1810 (Core)
mariaDB: mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

Also, here is an Ansible script that resembles the configuration on this machine:
```
- name: Installation of the Cerberus Testing server
  hosts: cerberus
  become: yes
  become_method: sudo
  tasks:
    - name: Install mariadb
      package:
        name: mariadb
        state: latest

    - name: Install mariadb-server
      package:
        name: mariadb-server
        state: latest

    - name: Start and Enable service mariadb, if not started
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install JDK 8
      package:
        name: java-1.8.0-openjdk
        state: latest

    - name: Install JDK 8 devel
      package:
        name: java-1.8.0-openjdk-devel
        state: latest

    - name: Get glassfish 4.1.2 release
      get_url:
        url: http://download.oracle.com/glassfish/4.1.2/release/glassfish-4.1.2.zip
        dest: /root/

    - name: Unpack glassfish
      shell: unzip /root/glassfish-4.1.2.zip -d /root/

    - name: Copy glassfish to /usr/local
      shell: rm -rf /usr/local/glassfish4 && cp -r /root/glassfish4 /usr/local

    - name: Ensure group "glassfish" exists
      group:
        name: glassfish
        state: present
      become: yes
      become_method: sudo

    - name: Add the user "glassfish"
      user:
        name: glassfish
        shell: /bin/bash
        groups: glassfish

    - name: Change the ownership of /usr/local/glassfish4 to glassfish
      file:
        dest: /usr/local/glassfish4
        owner: glassfish
        group: glassfish
        recurse: yes

    - name: copy glassfish4.service file
      copy:
        src: glassfish4.service
        dest: /etc/systemd/system/glassfish4.service
        owner: root
        group: root

    - name: Stop and Disable service glassfish4, cerberus will start it
      service:
        name: glassfish4
        state: stopped
        enabled: no

    - name: Download Cerberus Testing package
      get_url:
        url: https://sourceforge.net/projects/cerberus-source/files/cerberus-testing-4.0/Cerberus-4.0.zip/download
        dest: /root/Cerberus-4.0.zip

    - name: Unpack Cerberus
      shell: unzip /root/Cerberus-4.0.zip -d /root/

    - name: Copy config-mysql.sql script to context
      copy:
        src: config-mysql.sql
        dest: /root/config-mysql.sql
        owner: root
        group: root

    - name: Run the SQL script in mysql
      shell: cat /root/config-mysql.sql | mysql

    - name: Download mariadb connector
      get_url:
        url: https://downloads.mariadb.com/Connectors/java/connector-java-2.1.2/mariadb-java-client-2.1.2.jar
        dest: /usr/local/glassfish4/glassfish/lib/mariadb-java-client-2.1.2.jar

    - name: Modify cerberus installation variables
      lineinfile:
        dest: /root/Cerberus-4.0/bin/00Config.sh
        regexp: ".*GLASSFISHPATH.*"
        line: "export GLASSFISHPATH='/usr/local/glassfish4/glassfish/bin'"

    - name: Execute cerberus installation script
      shell: sh /root/Cerberus-4.0/bin/01AppServerConfig.mariadb.sh

    - name: Execute cerberus deploy script
      shell: sh /root/Cerberus-4.0/bin/02DeployApp.sh
```

Finally, the problem: When I try to execute a test case, I get a yellow warning popup with the following message:

>Unable to insert TestCaseExecutionInQueue [id=-1, test=Test-test, testCase=0001A, country=PT, environment=MANUAL, robot=local_robot, robotIP=null, robotPort=null, browser=null, browserVersion=null, platform=null, manualURL=1, manualHost=asd, manualContextRoot=asd, manualLoginRelativeURL=asd, manualEnvData=PROD, tag=tryout, screenshot=1, verbose=1, timeout=120, pageSource=0, seleniumLog=2, requestDate=null] due to null

Looking at the glassfish logs located at /usr/local/glassfish4/glassfish/domains/domain1/logs/server.log I see the following messages after I try to execute the test:

> [2019-07-01T19:12:58.861+0100] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=102 _ThreadName=Thread-8] [timeMillis: 1562004778861] [levelValue: 800] [[
  2019-07-01 19:12:58 ERROR TestCaseExecutionQueueDAO:1516 - Unable to execute query : java.sql.SQLSyntaxErrorException: (conn=782) Unknown column 'UsrCreated' in 'field list']]
> [2019-07-01T19:12:58.871+0100] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=102 _ThreadName=Thread-8] [timeMillis: 1562004778871] [levelValue: 800] [[
  2019-07-01 19:12:58 ERROR TestCaseExecutionQueueDAO:1754 - Unable to execute query : java.sql.SQLSyntaxErrorException: (conn=782) Unknown column 'DateModif' in 'field list']]
> [2019-07-01T19:12:58.872+0100] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=102 _ThreadName=Thread-8] [timeMillis: 1562004778872] [levelValue: 800] [[
  2019-07-01 19:12:58 WARN  AddToExecutionQueueV003:583 - Unable to insert TestCaseExecutionInQueue [id=-1, test=Test-test, testCase=0001A, country=PT, environment=MANUAL, robot=local_robot, robotIP=null, robotPort=null, browser=null, browserVersion=null, platform=null, manualURL=1, manualHost=asd, manualContextRoot=asd, manualLoginRelativeURL=asd, manualEnvData=PROD, tag=tryout, screenshot=1, verbose=1, timeout=120, pageSource=0, seleniumLog=2, requestDate=null] due to null]]
